### ISSUE TITLE
API ergonomics

### ISSUE THREAD

**Issue by QuarticCat** [judofyr/spice#9]
I like the idea of static dispatch very much. However, current API design requires users to invoke the forked function twice. That would be a problem when porting to Rust if the input has some non-copy values.

**Comment by QuarticCat** [comment]
Just came up with some ideas.

**Comment by judofyr** [comment]
Very interesting! Looking forward to seeing if you're able to improve this. The concept of "doing the work completely inline [e.g. static function calls]" did seem to be quite critical to make the overhead so small.

**Comment by QuarticCat** [comment]
Rayon's `join` API seems perfectly fit here. It has some advantages:

- It guarantees that forked tasks are joined before the end of the function. Thus we can safely borrow local variables. It's important for Rust API ergonomics. Otherwise we have to use `Arc` everywhere.
- It's generics over given functions. Thus the compiler knows exact types of given functions and perhaps can do static function calls automatically.
- It needs to return results anyway. Thus we don't need to allocate execute states separately, just wrap the given function to directly write to stack memory. It should be efficient since I've seen this in [kanal](https://github.com/fereidani/kanal).

Beside, we can extend the API to be like `(a, b, c).join()` to support arbitrary numbers of tasks. Just define a `Join` trait and use some macros to generate trait implementations for tuples.
